name: Run tests in parallel

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run
          browser: chrome
        continue-on-error: true

      - name: Verify reports
        run: ls cypress/reports/

      - name: Run script convert json to excel
        run: node cypress/scripts/json-to-excel.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: excel-report
          path: |
            cypress/reports
            cypress/reports/*.xlsx
      
      - name: Set artifact link
        id: set-artifact-link
        run: |
          ARTIFACT_PATH=$(echo "${{ github.event.workflow_run.artifacts_url }}" | sed 's|.*/artifacts/||')
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${ARTIFACT_PATH}"
          echo "ArtifactLink=${ARTIFACT_URL}" >> $GITHUB_ENV

  notify:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Imprime a VariÃ¡vel Secreta
        run: echo "Minha variÃ¡vel secreta Ã© ${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: ðŸ“£ Send teams notification
        uses: simbo/msteams-message-card-action@latest
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: Hello world!