name: Run tests in parallel

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run
          browser: chrome
        continue-on-error: true

      - name: Verify reports
        run: ls cypress/reports/

      - name: Run script convert json to excel
        run: node cypress/scripts/json-to-excel.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: excel-report
          path: |
            cypress/reports
          retention-days: 7

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
      
      - name: Set artifact link
        id: set-artifact-link
        run: |
          ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}"
          echo "ArtifactLink=${ARTIFACT_URL}" >> $GITHUB_ENV

      - name: üì£ Send teams notification
        uses: simbo/msteams-message-card-action@latest
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Cypress Excel Report
          color: 6aa84f
          message: <p>Clique abaixo para obter os artefatos gerados durante a √∫ltima execu√ß√£o dos testes!</strong></p>
          buttons: |
            Click here! ${{ env.ArtifactLink }}
          sections: |
            -
              activityTitle: Marco Antonio
              activitySubtitle: $(date +'%d/%m/%Y, %l:%M%P')
              activityImage: https://i.ibb.co/3mf34tL/perfil-linkedin.jpg
              facts:
                -
                  name: "Board:"
                  value: Resultado dos artefatos gerados dos testes
                -
                  name: "List:"
                  value: Name of list
                -
                  name: "Assigned to:"
                  value: Gest√£o de Qualidade
                -
                  name: "Due date:"
                  value: (none)
              text: Uma demonstra√ß√£o de como enviar uma mensagem para o Teams incluindo um link para os artefatos gerados durante a execu√ß√£o dos testes.

